### PR TITLE
fix black border of video card

### LINKED ISSUE #153: Black borders on youtube thumbnails
Issue: 
Screenshot 2023-05-17 at 17 06 51

## Possible solution: 
 - move border-radius to parent and hide overflow: 
 ```css
.cards.video .cards-card-image {
    border-top-left-radius: 16px;
    border-top-right-radius: 16px;
    overflow: hidden;
}
```
- zoom the thumbnail by 10% and remove the border radius: 
```css
.cards > ul > li img {
    transform: scale(1.1);
```
- maybe restrict this youtube videos, by only zooming youtube thumbnails: 
```css
.cards > ul > li img[src*="img.youtube.com"] {
  transform: scale(1.1);
}
```

### PR DESCRIPTION
**Pull request by FrancoisZhang**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #153 

Test URLs:
- Before: https://main--zemax--hlxsites.hlx.page/blogs/videos
- After: https://issue-153--zemax--hlxsites.hlx.page/blogs/videos

### CODE REVIEW

**Comment by kunwarsaluja** [comment]
@FrancoisZhang  Screenshot 2023-05-23 at 2 20 21 PM

**Comment by FrancoisZhang** [comment]
@kunwarsaluja check it again now, you check it too fast before I ask for review.
the border exists in origin thumbnail from youtube thumbnail BTW.

**Comment by kunwarsaluja** [comment]
@FrancoisZhang  Do you know why thumbnails are missing on Page 2 cards ? 

https://issue-153--zemax--hlxsites.hlx.page/blogs/videos?page=2

**Comment by kunwarsaluja** [comment]
hmm maybe it was the cache..I see them now

**Pull request merged**
